# Generated by Django 3.0.1 on 2019-12-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(default='Project Name', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='url',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
